[team#01][BE] 2주차 pr입니다
codesquad-members-2023/issue-tracker-max pull request #26
Opened 2023-08-04 02:35 UTC by he2joojo

## 이번 주 작업 내용 🔑

- 프론트 서버 배포
- 백엔드 서버 배포
- 메인화면의 열린이슈&닫힌이슈 목록 구현
- 라벨 관리페이지 구현
- 마일스톤 관리페이지 구현
- 메인화면의 필터 보내주는 기능 구현
- 이슈작성 및 상세화면의 필터 보내주는 기능 구현
- layer마다 테스트 코드 작성
- 통합 테스트 작성

## To Reviewer 👋

- dto가 너무 많은 것 같은데 dto를 재사용하는 것이 좋은지 아니면 필드가 다른 경우 dto를 모두 나누는 것이 좋은지 궁금합니다!

2023-08-04 08:41 UTC, pbg0205 requested changes
안녕하세요~ 나그, 조이
이번 주에 정말 많은 작업을 진행주셨네요! 테스트까지 꼼꼼하게 작성해주셔서 코드를 파악하는데 조금 더 편했어요 👍👍
수고 많으셨습니다

### 질문에 대한 피드백

리뷰에 질문에 코멘트를 먼저 드리면 개인적으로는 VO 는 재사용하지 않는 방법을 선호하고 있어요. 그 이유는 여러 API 가 VO 를 재사용하여 사용하는 경우를 들었을 때 특정 API 의 요구사항이 변경되었을 때 VO 를 재사용 한다면 이후에 DTO 를 분리해야 하거나 두가지 요구사항을 모두 만족하는 방대한 VO 가 생성될 수 있어요. 그럴 경우 이후에 유지보수가 어려워질 수 있어 지양하는 편입니다. 

<br>

코멘트에 여러 comment 를 대표하는 리뷰들(예를 들어, assertAll(), unused import, Repository 생성자 주입)은 전체적으로 적용해주시면 될 것 같습니다! 한번은 코드에 관해 검토도 하고 리팩토링하는 의미로 `Request Change` 하였습니다. 리뷰 마감이 일요일까지라 혹시 반영이 어려우시면 말씀 부탁드려요! 리뷰 검토 및 리팩토링 해보시고 궁금한 내용 있으시면 언제든 연락주시고 화이팅 입니다🔥🔥

2023-08-04 08:41 UTC, pbg0205 commented on be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/MilestoneController.java
> +    private final MilestoneService milestoneService;
`MilestoneService` 을 구현체로 의존성을 주입하고 있네요. 인터페이스를 주입하는 방법과 구현체를 주입하는 방식의 장단점에 대해 고민해보시면 좋을 것 같습니다~

2023-08-04 08:41 UTC, pbg0205 commented on be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/MilestoneController.java
> +    }
두 API 는 @PathVariable 을 사용하면 중복 코드를 줄일 수 있을 것 같습니다. `MilestoneService`, `MilestoneRepository` 에서도 두 메서드를 확인해보면 파라미터만 다르고 로직이 똑같아 보여서요. `open`, `closed` 를 @PathVariable 로 선언하고 메서드 파라미터로 전달받으면 되지 않을까 하는데 두분의 생각은 어떠신가요?

2023-08-04 08:41 UTC, pbg0205 commented on be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/annotation/RepositoryTest.java
> +import org.springframework.boot.test.context.SpringBootTest;
사용하지 않는 어노테이션은 제거 부탁드려요~

2023-08-04 08:41 UTC, pbg0205 commented on be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/MilestoneRepository.java
> +    }
`NamedParameterJdbcTemplate` 의 경우에는 spring boot 의 auto configuration 중에 `NamedParameterJdbcTemplateConfiguration` 에서 자동으로 빈을 등록시켜줘서 생성자 주입으로 받으시면 될 것 같아요😃

```java
    public MilestoneRepository(NamedParameterJdbcTemplate namedParameterJdbcTemplate) {
        this.namedParameterJdbcTemplate = namedParameterJdbcTemplate;
    }
```

2023-08-04 08:41 UTC, pbg0205 commented on be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/annotation/RepositoryTest.java
> +@JdbcTest
@JdbcTest 는 @Component 어노테이션을 스캔하지 않는다고 하네요ㅎㅎ 해당 부분 참고하셔서 테스트 작성하시면 될 것 같아요 

- https://docs.spring.io/spring-boot/docs/2.6.14/reference/htmlsingle/#features.testing.spring-boot-applications.autoconfigured-jdbc
> @JdbcTest is similar to @DataJpaTest but is for tests that only require a DataSource and do not use Spring Data JDBC. By default, it configures an in-memory embedded database and a JdbcTemplate. Regular @Component and @ConfigurationProperties beans are not scanned when the @JdbcTest annotation is used. @EnableConfigurationProperties can be used to include @ConfigurationProperties beans.

2023-08-04 08:41 UTC, pbg0205 commented on be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/MilestoneRepositoryTest.java
> +        assertThat(actual.get(3).getName()).isEqualTo("마일스톤 3");
여러 내용을 검증할 경우에는 `assertAll()` 을 사용하는 것을 권장합니다👍👍(현재 테스트에서는 만약에 3, 4, 5번째가 검증이 안될 경우에 3번만 틀렸다는 메세지를 전달해줍니다)

2023-08-04 08:41 UTC, pbg0205 commented on be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/service/MilestoneServiceTest.java
> +        assertThat(actual.getMilestoneDetailsInformations().size()).isEqualTo(3);
의미를 명확히 구분하기 위해서 `given-when-then` 으로 추가해보시면 가독성이 좋아질 것 같습니다ㅎㅎ

2023-08-04 08:41 UTC, pbg0205 commented on be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/integration/MilestoneIntegrationTest.java
> +                .andExpect(jsonPath("$.milestones.[0].name").value("마일스톤 0"))
`expectAll()` 과 `andExpect()` 차이에 대해 학습해보세요 😃

2023-08-04 08:41 UTC, pbg0205 commented on be/src/test/resources/schema/schema.sql
> +);
(참고만 해주세요) 일반적으로 백엔드에서 데이터를 생성 및 변경 시점을 관리하는 `createdDate`, `modifiedDate` 를 추가합니다

2023-08-04 08:41 UTC, pbg0205 commented on be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/IssueController.java
> +    }
이 부분도 `@PathVariable` 로 open, closed 를 관리하면 service 와 repository 의 중복 코드를 제거할 수 있을 것 같아요!

2023-08-04 08:41 UTC, pbg0205 commented on be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/IssueController.java
> +    }
이 부분은 필터를 적용하기 위해 필요한 요소(저자, 마일스톤, 라벨) 를 가지고 오는 api 인가 보네요

2023-08-04 08:41 UTC, pbg0205 commented on be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/repository/MemberRepository.java
> +    }
클린 코드에서는 `그릇된 정보를 피하기` 라는 주제로 약어를 지양하고 있어요~ 저도 약어를 사용하면 여러 사람이 볼 때 다시 약어가 무엇인지 찾아가야 하는 불편함이 있어 지양하고 있습니다. 하지만 정답은 없는 부분이라서 두 분의 생각도 궁금하네요~
한번 고민해보시면 좋을 것 같아 참고할 자료 관련해서 첨부 드립니다ㅎㅎ
- https://ittrue.tistory.com/336

2023-08-04 08:41 UTC, pbg0205 commented on be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/response/MilestonePageResponse.java
> +import codesquad.kr.gyeonggidoidle.issuetracker.domain.milestone.service.information.MilestoneDetailsInformation;
사용하지 않는 import 는 제거해주세요~ intellij 에서 미사용 import 는 자동으로 제거해주는 옵션이 있는 것으로 알고 있어요. 한번 검색해보시고 적용해보시면 좋을 것 같습니다ㅎㅎ

2023-08-04 08:41 UTC, pbg0205 commented on be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/annotation/ServiceTest.java
> +public @interface ServiceTest {
의미를 명확하게 할 수 있는 복합 어노테이션을 처리하는 것 좋네요👍👍

2023-08-04 08:41 UTC, pbg0205 commented on be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/IssueControllerTest.java
> +
마이너한 부분이지만 일관성을 위해 개행을 추가하면 좋을 것 같습니다!

2023-08-04 08:41 UTC, pbg0205 commented on be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/IssueRepositoryTest.java
> +    void openIssuetest() {
테스트 코드이기 때문에 test 라는 접미사는 없어도 될 것 같아요~

2023-08-04 08:41 UTC, pbg0205 commented on be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/IssueRepository.java
> +    }
이 부분도 이미 NamedParameterJdbcTemplate 이 springboot에 의해 등록되어 있기 때문에 생성자 주입으로 처리해주셔도 될 것 같아요~

```java
    public IssueRepository(NamedParameterJdbcTemplate namedParameterJdbcTemplate) {
        this.namedParameterJdbcTemplate = namedParameterJdbcTemplate;
    }
```

2023-08-04 08:41 UTC, pbg0205 commented on be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/repository/MemberRepository.java
> +    }
NamedParameterJdbcTemplate 만 생성자 주입해주세요~

2023-08-04 08:41 UTC, pbg0205 commented on be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/MilestoneRepositoryTest.java
> +    }
@JdbcTest 특성상 @Component 어노테이션을 스캔하지 않아서 이와 같이 처리하신 것 같아요. 이럴 경우에는 `@TestConfiguration` 과 `@Import` 를 사용해서 해결하는 방법도 있어요. 이후에 한번 공부해보세요~

2023-08-04 08:49 UTC, pbg0205 commented
그리고 추가 질문사항이 있어 코멘트 드려요!

1. application.yml 에 해당 옵션을 사용하신 이유에 대해서 설명 부탁드려요 🙏

```yml
jpa:
    hibernate:
    ddl-auto: none
```

2. 패키지 구조를 보니까 layered architecture 를 사용하고 계신데 domain 하위에 controller, repository, service 를 선언하신 이유가 궁금합니다. 처음보는 형태라 다른 의도가 있을실 것 같아 문의드려요!

<img width="336" alt="image" src="https://github.com/codesquad-members-2023/issue-tracker-max/assets/48561660/2630f838-8176-47fa-8072-9edc1a51f35d">

2023-08-04 09:45 UTC, pbg0205 approved these changes

2023-08-05 05:31 UTC, pbg0205 commented
나그, 조이와 일정 협의하여 차주 리뷰 내용에서 검토할 예정입니다.

2023-08-05 05:31 UTC, merged

2023-08-07 02:25 UTC, n-aa-g commented on be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/IssueController.java
> +    }
넵 맞습니다~

2023-08-07 02:51 UTC, he2joojo commented on be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/IssueController.java
> +    }
이 부분은 '필터 적용한 이슈 가져오기' api 짜면서 통합하겠습니다!:)

2023-08-07 12:38 UTC, n-aa-g commented on be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/MilestoneController.java
> +    private final MilestoneService milestoneService;
인터페이스를 주입하여 확장에 유연한 구조를 가질 수 있는 장점은 분명히 있습니다. 
하지만 지금 구현체를 변경할 계획이 없기에 인터페이스를 선언하는데 시간이 걸린다고 생각하여 구현체들을 다 bean으로 등록했습니다.
만약 구현하면서 구현체를 변경할 경우가 생긴다면 인터페이스를 선언하고 Bean을 관리할 것 같습니다.

2023-08-07 12:44 UTC, nag0124 commented on be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/repository/MemberRepository.java
> +    }
넵 약어를 없앴습니다!

2023-08-07 12:50 UTC, n-aa-g commented on be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/MilestoneController.java
> +    }
위의 api들은 임시로 만들어 놓은 api들입니다.
맨처음 프로젝트를 시작할 때 저희는 필터를 만들고 적용하는데 시간이 오래 걸릴 것이라 생각했습니다.
그리고 메인 페이지를 만드는 데 필터 기능이 필요 했고요.
하지만 필터를 다 구현하고 메인페이지를 구현하는 것이 비효율적이라고 생각했습니다.
필터를 다 구현하고 메인페이지를 만들게 되면 기능이 무거워 지고, 프론트와의 연결에서도 오류가 발생할 가능성이 크다고 판단했기 때문입니다.
따라서 위의 두 api를 임의로 만들어 프론트에게 통신이 어떻게 될지 미리 알려주고 프론트와의 연결에서 발생할 수 있는 문제들을 먼저 처리한뒤, 이번주에 필터를 만들고 적용한다면 api를 삭제할 생각입니다.

2023-08-07 12:50 UTC, n-aa-g commented on be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/IssueController.java
> +    }
넵 알겠습니다 ㅎㅎ

2023-08-07 13:16 UTC, n-aa-g commented
쿠퍼의 리뷰 중에서 중복되는 내용은 여기에 답하겠습니다.
- Repository에 DataSource대신 NamedParameterJdbcTemplate 주입해주세요
저번에 작업했던 코드를 가져오는 과정에서 생각없이 datasource를 주입했습니다.
이 기회에 @JdbcTest, @DataJdbcTest를 학습했고 @JdbcTest에서 datasource와 JdbcTemplate를 주입할 수 있다는 것을 배웠습니다.
또한 알려주신 TestConfiguration과 Import 어노테이션을 학습하여 적용하고 싶었지만 아직 깊이가 부족해 적용에는 실패했습니다.
그래서 변경사항으로는 Repository에는 기존의 생성자를 삭제하고 @RequiredArgumentConstructor를 적용하여 깔끔한 코드가 되도록 했습니다.
또한 Repository에는 JdbcTemplate과 Datasource만 스캔하기에 NamedParameterJdbcTemplate을 생성자에서 넣어주었습니다.

- andExpect() 대신 andExpectAll()을 써주세요.
json을 제대로 반환하는지 확인하는 부분은 andExpectAll()메서드를 사용하여 하나의 단위임을 보였습니다.

- assertThat()대신 assertAll()을 써주세요.
기존의 여러개의 assertThat()에서는 위의 assertThat()이 실패하면 아래 assertThat()은 실행되지 않습니다.
이를 보완하기 위해, 여러개의 assertThat()의 실행을 보장하기 위해 assertAll()을 쓰고 그 안에 assertThat()을 쓰면 됩니다.
저는 여기에 assertSoftly()라는, assertAll()처럼 여러 assertThat()문 실행을 보장해주는 기능이 있고 실패하면 몇 번째 줄에서 실패했는지 친절히 알려주는 코드로 테스트 코드를 수정했스니다.

- given, when, then 넣어주세요~
가독성을 위해 위의 주석을 추가했습니다.

- jpa 설정은 왜들어있나요?
이전 코드에서 설정파일을 가져오면서 같이 왔습니다. 이번 프로젝트에서 jpa를 쓸 일이 없기에 삭제했습니다.

- 쓰지 않는 import문 정리, test 메서드에 test 삭제해주세요~
수정... 완료... 이제 살려주세요... 다한거죠...?

2023-08-07 16:10 UTC, pbg0205 commented on be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/MilestoneController.java
> +    }
임시 API 를 작성해주신 의도는 이해합니다. 하지만 비록 임시 API 이지만 설계적인 측면에서 조금 더 고민을 하셨으면 합니다. 같은 로직은Service, Repository 에서 open, closed 을 제외만 모든 로직이 동일하므로 코드를 작성하고 제거하는 범위가 더욱 넓어지기 때문입니다.

2023-08-08 05:01 UTC, he2joojo commented
> 패키지 구조를 보니까 layered architecture 를 사용하고 계신데 domain 하위에 controller, repository, service 를 선언하신 이유가 궁금합니다. 처음보는 형태라 다른 의도가 있을실 것 같아 문의드려요!

domain으로 먼저 패키지를 나누고 그 아래에 controller, service, repository를 둬서 한 패키지 안에 클래스가 너무 많아지지 않게 하려고 했습니다! 특히 dto를 한 패키지에 두지 않고 domain별로 패키지를 나눠서 어디에서 사용되는지 구별하려고 했습니다!

2023-08-08 08:24 UTC, pbg0205 commented
@he2joojo @n-aa-g 도메인을 구분하는 용도라면 domain package 를 제거하고 issue, label, milestone 으로 가져가셔도 될 것 같아요. domain package 는 주로 엔티티를 관리하는 패키지로 사용되고 도메인을 명명하지 않아도 의미가 명확해보여서요. 오히려 issue package 내부에 domain pakcage 를 선언하고 Issue class 를 관리하는 용도로 사용하시는 것이 더욱 명확해 보입니다.